### ISSUE TITLE
Does not support current Password Box version

### ISSUE THREAD

**Issue by lsaturno** [klingenm/passwordbox-export#1] opened 2015-05-07 14:59 UTC
Hi Klingenm,

I´m no programmer but followed your guide to export from passwordbox. After I pasted the JS file content and pressed enter, I received an "Undefined" message and nothing else.

Can you give me some tips on what I'm missing?

Thanks in advance.

Luis

**Comment by klingenm** [comment] 2015-05-17 12:02
Hi! Could you please send me a screenshot or similar so that I can look for
possible errors? Just "Undefined" is a bit hard to go on.

Best regards, Magnus

**Comment by jpmurray** [comment] 2015-05-22 12:21
I'm getting it also, and [it really only gives Undefined](http://imgur.com/eSvgXLc)...

**Comment by klingenm** [comment] 2015-05-23 15:05
Oh, that text "Undefined" is not an error, it is the return value from the
operation of reading the code, sortof. There seems to be some errors, to
see them, click the red x to see the error console, and send me a
screenshot of that also, then I might be able to help.

**Comment by jpmurray** [comment] 2015-05-24 18:56
@klingenm sadly, I went on and just exported manually, so I can't reproduce the error. Maybe @lsaturno will chime in?

**Comment by n0v3xx** [comment] 2015-06-09 21:31
I have the same problem ... look at my screen:
https://goo.gl/photos/qc4ozgh8Wp4tqfxB6
https://goo.gl/photos/eEkQeBzyuyPiV2MU7

**Comment by klingenm** [comment] 2015-06-10 09:24
Hi!

The Undefined message comes as mentioned earlier from the fact that the loading of the code returns nothing. In itself it presents no error. In the README I state that after loading the code you need to run one of the export functions to export the database to your clipboard, running that would in the supported version have exported all the passwords.

Now it seems that Password Box have made a complete rewrite, none of the namespaces that my hack calls upon exist anymore.

I'll see if I can find the time to update to the current version.

**Comment by n0v3xx** [comment] 2015-06-10 12:07
Ok thanks. it would be nice.

**Comment by wesselvdv** [comment] 2015-06-20 13:17
@klingenm It's quite simple actually, they switched from AES to RSA. So changing the decrypt function from 'FA.Background.decryptWithAES' to 'FA.Background.decryptWithRSA' does the trick!

**Comment by wesselvdv** [comment] 2015-06-20 13:35
@klingenm I seem to have fixed it. They're using an key to encrypt the passwords now. That key is stored in 'FA.Background.fa_member.key', this key needs to be supplied to the decrypt function as the second parameter! It only seems to work for the 'password_k' variable, as the memo_k variable is empty.

EDIT:

This is weird, the password is already available in the 'item.attributes' object!! Decrypted and ready for use. You don't even need the decrypt function. You can safely comment the entire line out.

**Comment by NeoMod** [comment] 2015-08-11 11:16
@wesselvdv Could you please elaborate more on how to solve the problem? I would be really glad to use this script to sump all of my passwords and get away from PasswordBox.

**Comment by justinkelly** [comment] 2015-08-12 00:55
hey guys - any update on this? - currently i cant add new passwords to PasswordBox due to hitting some password limit - and can't export my current ones :(

**Comment by Brrrknee** [comment] 2015-08-13 01:11
Magnus, the chrome dev tool has multiple windows, and none seem to want me to paste into them... explicitly which window do we paste the js code, and where (over/replace xxx, before xxx, after xxx)?
_this is a very important tool_, as Intel (bought McAfee bought passwordbox) and is ignoring the tool.  their substitute "TrueKey" is a real POS and defaults to using camera/facial recognition which hasn't worked yet in two weeks of beta release.  they're selling a pile of crap.

If the existing script will work on current pwb version with a js tweak(see above?), please post that explicit line/lines- I have 170 passwords and this hack of yours will make the exit from pwb much easier.  Thanks!
If anyone else had gotten it to work, please note the js tweak... thanks

**Comment by justinkelly** [comment] 2015-08-13 03:18
@Brrrknee you need to paste it in the console window and press enter - that said the script doesnt do anything for me at the moment - hopefully someone can fix this up so we can get our data out

**Comment by Brrrknee** [comment] 2015-08-13 11:28
thx

**Comment by Brrrknee** [comment] 2015-08-13 22:03
I pasted it into the console, ‘enter’ (getting the “undefined” the forum threads have already described as not an issue), then what command do I enter to run the exportCsvToClipboard?  I’ve tried 

exportCsvToClipboard, 

exportCsvToClipboard(), 

eval exportCsvToClipboard(),

call exportCsvToClipboard …

each with/wo parenthesis, not sure how to get it attempted (I do see from discussion that it would likely not yet work, as there is some latest PB changes, but I want to watch it myself to see if I can determine a means to adjust it myself)

I’d not worked with the chrome toolkit before –sorry for sounding daft!

**Comment by lfbarbieri** [comment] 2015-08-14 18:07
This code is great, I too am fed up with PWB not being updated and was looking for a way to get these passwords exported.

I run across the same issues these last few posts have mentioned.

But I got it working by doing the following:
1. Go to "Console" tab in the Developer Tools as mentioned in the Readme
2. Paste from export.js only lines 6 thru 131.  In other words I skipped all the module stuff.
3. I then typed in: "exportCsv()" into the bottom line and it worked, the CSV text came back as a result.
4. Copy & Paste into text editor/excel.
5. Should now be able to import into any other password manager.

Hope that helps.

Luciano

**Comment by Brrrknee** [comment] 2015-08-14 18:23
I updated it to work in the most recent pwb:
1.     In current PWB it is

a.     FA_version

b.     "1.38.11.4204"
1. ```
      There is no item.BelongsToMe; I //commented this part out—couldn’t find a relevant item.xxx() function or attribute similar
   ```
2. ```
   FA.Background.assets.models.forEach(function (item) {
   ```
3. ```
         if (!item.belongsToMe()) {  //this attribute doesn’t exist
   ```
4. ```
           return;
   ```
5. ```
         }
   ```

I also exported, just in case it meant anything to other pwd tools, the attributes.settings.subdomain_only as True/False

I added a few additional fields to the export column fields.

To run it, after pasting the attached code into console, enter

Window.MK.exportCsvToClipboard()

Recovered 169 in 1 second!

Thanks to the original author!

From: lfbarbieri [mailto:notifications@github.com] 
Sent: Friday, August 14, 2015 1:08 PM
To: klingenm/passwordbox-export
Cc: Brrrknee
Subject: Re: [passwordbox-export] Does not support current Password Box version (#1)

This code is great, I too am fed up with PWB not being updated and was looking for a way to get these passwords exported.

I run across the same issues these last few posts have mentioned.

But I got it working by doing the following:
1.  Go to "Console" tab in the Developer Tools as mentioned in the Readme
2.  Paste from export.js only lines 6 thru 131. In other words I skipped all the module stuff.
3.  I then typed in: "exportCsv()" into the bottom line and it worked, the CSV text came back as a result.
4.  Copy & Paste into text editor/excel.
5.  Should now be able to import into any other password manager.

Hope that helps.

Luciano

—
Reply to this email directly or view it on GitHub https://github.com/klingenm/passwordbox-export/issues/1#issuecomment-131197030 .  https://github.com/notifications/beacon/AKr84M6gKSrjtyOOFaxHuAx8oBrG1J6Oks5oniXxgaJpZM4ESkUj.gif

**Comment by NeoMod** [comment] 2015-08-14 18:58
@lfbarbieri Just tryied your method but Console Output was different, another error I suppose:

You are running PasswordBox 1.38.11.4204. This has only been tested on 1.38.9.4120
VM405:34 Uncaught TypeError: JSON.decode is not a function(…)(anonymous function) @ VM405:34getDecryptedRecords @ VM405:26exportCsv @ VM405:95(anonymous function) @ VM422:2InjectedScript._evaluateOn @ VM117:875InjectedScript._evaluateAndWrap @ VM117:808InjectedScript.evaluate @ VM117:664

@Brrrknee I've also tried applying suggested modification but due to my lack of expertie with JS something went wrong and result is just another error.

Could you please FORK the project and apply your changes to the code?

**Comment by Brrrknee** [comment] 2015-08-14 19:02
Sorry, seems outlook blocked the .js as a threat… I’m forwarding as a zip

**Comment by NeoMod** [comment] 2015-08-14 19:06
Thank you very much @Brrrknee !   :+1: 

Feel free to drop a line to n3omod (at) gmail because I suppose direct reply to GitHub Comments won't support any kind of attachment.

**Comment by AnilRh** [comment] 2015-09-09 16:21
I just used the script successfully on Chrome (osx) with PWB extension 1.38.11.4204.

Thanks!

**Comment by NeoMod** [comment] 2015-09-12 18:36
Sorry AnilRh, 
but I just re-tested on WIN 10 and Chrome Version 47.0.2507.0 canary (64-bit) and it still doesen't work. 
Output is still "undefined", also latest PWB Version available is still 1.38.11.4170.

**Comment by klingenm** [comment] 2015-09-28 17:10
This seems to be an issue with either how the guide is written or how it's read. As some get it working it seems it is functional (I no longer have the plugin, nor plan to install it again). If somebody wants to, I'm gladly merge any pull-requests improving the guide.

@NeoMod, output is undefined but stuff has been created on the scope, you could then run the functions that are listed in the Readme.

I'm closing this as not a bug...

**Closed as completed by klingenm** 2015-09-28 17:10 UTC
Labels: invalid

**Comment by NeoMod** [comment] 2015-09-28 17:29
Thank you @klingenm I will try again with even much more attention at instructions and I'll provide an update in case I found a significant "bug" other than the "undefined": I'm sorry for pointing at it as a bug.

Thank you again for your time while helping us getting out PB nightmare!
